#!/bin/bash

echo -e "\e[33m  
   _____ _   ______________________  ____  __    ________________
  / ___// | / /  _/ ____/ ____/ __ \/ __ \/ /   /  _/ ____/ ____/
  \__ \/  |/ // // /_  / /_  / /_/ / / / / /    / // /   / __/
 ___/ / /|  // // __/ / __/ / ____/ /_/ / /____/ // /___/ /___
/____/_/ |_/___/_/   /_/   /_/    \____/_____/___/\____/_____/  "

echo "'Thank you for choosing sniffpolice as your networking tool' - MO"

# Getting users subnet.
echo "Is this your subnet you'd like to police?[y/n/q]"
subnet=$(ip -o -f inet addr show | awk '/scope global/ {print $4}' |grep -m1 "")
echo $subnet

valid=true

while [ "$valid" = true ]
do
	echo -n ":"
	read answer
	
	if [ $answer = "y" ]
	then
		valid=false
	elif [ $answer = "n" ] 
	then 
		echo -n "Please enter your subnet: "
		read subnet
		valid=false
	elif [ $answer = "q" ]
	then 
		exit 0
	else
		echo "Please choose a valid option.[y/n/q]"
	fi
done

# Confirmed subnet. Now gathering ip addresses on the subnet.
echo -e "\e[32mGathering host ip's on the network..."
arr=( $(nmap $subnet | grep -oE "\b([0-9]{1,3}\.){3}[0-9]{1,3}\b" | sort | uniq | sort) )

for ip in "${arr[@]}"
do
	echo ""
	echo "Poking $ip for sniffing..."
	sleep 5
	sudo nmap -q --script=sniffer-detect "$ip"
done
